title: AirSupplier
description:  Discord Python Documentation
remote_theme: tuur29/pages-themes-cayman
darkmode: true
color:
  header: "#000"
  gradient_left: "#000fff"
  gradient_right: "#fff000"
logo_url: https://airsupplier.github.io/assets/img/airsupplier.png
